#!/usr/bin/sh
xrandr --dpi 96
bspc rule -r "*"
killall flameshot 
killall nm-applet
sxhkd &
$HOME/.config/polybar/launch.sh &
wmname compiz
export _JAVA_AWT_WM_NONREPARENTING=1
nm-applet &
flameshot &
nitrogen --restore &
exec --no-startup-id xsettingsd &
bspc monitor -d I II III IV V 

# Remove top padding in monocle mode
# for side in top ; do bspc config ${side}_monocle_padding 0; done
bspc config top_padding		 0
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#f0c674" 
bspc config presel_feedback_color "#bd93f9"

bspc rule -a Zathura state=gapless_monocle 
bspc rule -a SummertimeSaga desktop='^4' state=gapless_monocle 
bspc rule -a "zoom " desktop='^5' state=floating
bspc rule -a Godot state=floating
bspc rule -a Gimp-2.10 desktop='^4' state=gapless_monocle follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a virtualbox desktop='^3' follow=on
bspc rule -a rofi state=floating
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Virt-manager desktop='^3' state=gapless_monocle follow=on
